#对象的配置
server:
  port: 8082
spring:
  profiles:
    active:
      - prod
---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8084
spring:
  profiles: prod
---



#数据库配置
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/girls?characterEncoding=utf8&serverTimezone=GMT%2B8&&useSSL=false
      #    配置监控统计拦截的files,去掉后监控界面sql则无法显示，‘wall’用于防火墙
      filter: stat,wall,log4j
      #    最大活跃数
      max-active: 20
      #    初始化数量
      initial-size: 1
      #    最大连接等待超时时间
      max-wait: 60000
      #    打开PSCache,指定每个连接PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #    通过connection-properties属性，打开mergeSql功能;慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  main:
    allow-bean-definition-overriding: true


  Jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  type-aliases-package: com.example.demo.bean
  mapper-locations:
    - classpath:mapper/*Mapper.xml
