server:
  port: 8888


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8&&useSSL=false
#    url: jdbc:mysql://localhost:3306/girls?characterEncoding=utf8&serverTimezone=GMT%2B8&&useSSL=false
    username: root
    password: 123456
    druid:
      max-active: 20
      initial-size: 1
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter: stat,wall,log4j

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
mybatis:
  type-aliases-package: com.example.demo.bean
  mapper-locations:
    - classpath:mapper/*.xml

