package com.example.demo.bean;

import java.util.Date;
import java.util.List;

/**
 * @Author:Goffy
 */
public class HqThsPark {
    /**
     * 图片 非数据库字段
     */
    private List<String> imgRes;
    private Integer parkType;
    private String num;
    private Byte deviceType;
    private Byte proprietaryFlag;

    public Byte getProprietaryFlag() {
        return proprietaryFlag;
    }

    public void setProprietaryFlag(Byte proprietaryFlag) {
        this.proprietaryFlag = proprietaryFlag;
    }

    public Integer getParkType() {
        return parkType;
    }

    public void setParkType(Integer parkType) {
        this.parkType = parkType;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    public Byte getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(Byte deviceType) {
        this.deviceType = deviceType;
    }

    public List<String> getImgRes() {
        return imgRes;
    }

    public void setImgRes(List<String> imgRes) {
        this.imgRes = imgRes;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.name
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.linkman
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.tel
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.email
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.address
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.longitude
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.latitude
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.total
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.empty
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer empty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.company_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.opening_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private String openingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.closing_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private String closingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.charging_rules_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer chargingRulesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.charge_type
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Byte chargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.emptybase
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer emptybase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.location_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.rel_park_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer relParkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.publish_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.flag
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.create_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.update_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_hq_ths_park.version
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.id
     *
     * @return the value of parking_hq_ths_park.id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.id
     *
     * @param id the value for parking_hq_ths_park.id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.name
     *
     * @return the value of parking_hq_ths_park.name
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.name
     *
     * @param name the value for parking_hq_ths_park.name
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.linkman
     *
     * @return the value of parking_hq_ths_park.linkman
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.linkman
     *
     * @param linkman the value for parking_hq_ths_park.linkman
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.tel
     *
     * @return the value of parking_hq_ths_park.tel
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.tel
     *
     * @param tel the value for parking_hq_ths_park.tel
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.email
     *
     * @return the value of parking_hq_ths_park.email
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.email
     *
     * @param email the value for parking_hq_ths_park.email
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.address
     *
     * @return the value of parking_hq_ths_park.address
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.address
     *
     * @param address the value for parking_hq_ths_park.address
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.longitude
     *
     * @return the value of parking_hq_ths_park.longitude
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.longitude
     *
     * @param longitude the value for parking_hq_ths_park.longitude
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.latitude
     *
     * @return the value of parking_hq_ths_park.latitude
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.latitude
     *
     * @param latitude the value for parking_hq_ths_park.latitude
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.total
     *
     * @return the value of parking_hq_ths_park.total
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.total
     *
     * @param total the value for parking_hq_ths_park.total
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.empty
     *
     * @return the value of parking_hq_ths_park.empty
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getEmpty() {
        return empty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.empty
     *
     * @param empty the value for parking_hq_ths_park.empty
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setEmpty(Integer empty) {
        this.empty = empty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.company_id
     *
     * @return the value of parking_hq_ths_park.company_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.company_id
     *
     * @param companyId the value for parking_hq_ths_park.company_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.opening_time
     *
     * @return the value of parking_hq_ths_park.opening_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public String getOpeningTime() {
        return openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.opening_time
     *
     * @param openingTime the value for parking_hq_ths_park.opening_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setOpeningTime(String openingTime) {
        this.openingTime = openingTime == null ? null : openingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.closing_time
     *
     * @return the value of parking_hq_ths_park.closing_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public String getClosingTime() {
        return closingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.closing_time
     *
     * @param closingTime the value for parking_hq_ths_park.closing_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setClosingTime(String closingTime) {
        this.closingTime = closingTime == null ? null : closingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.charging_rules_id
     *
     * @return the value of parking_hq_ths_park.charging_rules_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getChargingRulesId() {
        return chargingRulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.charging_rules_id
     *
     * @param chargingRulesId the value for parking_hq_ths_park.charging_rules_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setChargingRulesId(Integer chargingRulesId) {
        this.chargingRulesId = chargingRulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.charge_type
     *
     * @return the value of parking_hq_ths_park.charge_type
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Byte getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.charge_type
     *
     * @param chargeType the value for parking_hq_ths_park.charge_type
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setChargeType(Byte chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.emptybase
     *
     * @return the value of parking_hq_ths_park.emptybase
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getEmptybase() {
        return emptybase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.emptybase
     *
     * @param emptybase the value for parking_hq_ths_park.emptybase
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setEmptybase(Integer emptybase) {
        this.emptybase = emptybase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.location_id
     *
     * @return the value of parking_hq_ths_park.location_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.location_id
     *
     * @param locationId the value for parking_hq_ths_park.location_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.rel_park_id
     *
     * @return the value of parking_hq_ths_park.rel_park_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getRelParkId() {
        return relParkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.rel_park_id
     *
     * @param relParkId the value for parking_hq_ths_park.rel_park_id
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setRelParkId(Integer relParkId) {
        this.relParkId = relParkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.publish_time
     *
     * @return the value of parking_hq_ths_park.publish_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.publish_time
     *
     * @param publishTime the value for parking_hq_ths_park.publish_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.flag
     *
     * @return the value of parking_hq_ths_park.flag
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.flag
     *
     * @param flag the value for parking_hq_ths_park.flag
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.create_time
     *
     * @return the value of parking_hq_ths_park.create_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.create_time
     *
     * @param createTime the value for parking_hq_ths_park.create_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.update_time
     *
     * @return the value of parking_hq_ths_park.update_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.update_time
     *
     * @param updateTime the value for parking_hq_ths_park.update_time
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_hq_ths_park.version
     *
     * @return the value of parking_hq_ths_park.version
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_hq_ths_park.version
     *
     * @param version the value for parking_hq_ths_park.version
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_hq_ths_park
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HqThsPark other = (HqThsPark) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getLinkman() == null ? other.getLinkman() == null : this.getLinkman().equals(other.getLinkman()))
                && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
                && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
                && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
                && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
                && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
                && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()))
                && (this.getEmpty() == null ? other.getEmpty() == null : this.getEmpty().equals(other.getEmpty()))
                && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
                && (this.getOpeningTime() == null ? other.getOpeningTime() == null : this.getOpeningTime().equals(other.getOpeningTime()))
                && (this.getClosingTime() == null ? other.getClosingTime() == null : this.getClosingTime().equals(other.getClosingTime()))
                && (this.getChargingRulesId() == null ? other.getChargingRulesId() == null : this.getChargingRulesId().equals(other.getChargingRulesId()))
                && (this.getChargeType() == null ? other.getChargeType() == null : this.getChargeType().equals(other.getChargeType()))
                && (this.getEmptybase() == null ? other.getEmptybase() == null : this.getEmptybase().equals(other.getEmptybase()))
                && (this.getLocationId() == null ? other.getLocationId() == null : this.getLocationId().equals(other.getLocationId()))
                && (this.getRelParkId() == null ? other.getRelParkId() == null : this.getRelParkId().equals(other.getRelParkId()))
                && (this.getPublishTime() == null ? other.getPublishTime() == null : this.getPublishTime().equals(other.getPublishTime()))
                && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_hq_ths_park
     *
     * @mbg.generated Sun Sep 29 17:50:42 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getLinkman() == null) ? 0 : getLinkman().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        result = prime * result + ((getEmpty() == null) ? 0 : getEmpty().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getOpeningTime() == null) ? 0 : getOpeningTime().hashCode());
        result = prime * result + ((getClosingTime() == null) ? 0 : getClosingTime().hashCode());
        result = prime * result + ((getChargingRulesId() == null) ? 0 : getChargingRulesId().hashCode());
        result = prime * result + ((getChargeType() == null) ? 0 : getChargeType().hashCode());
        result = prime * result + ((getEmptybase() == null) ? 0 : getEmptybase().hashCode());
        result = prime * result + ((getLocationId() == null) ? 0 : getLocationId().hashCode());
        result = prime * result + ((getRelParkId() == null) ? 0 : getRelParkId().hashCode());
        result = prime * result + ((getPublishTime() == null) ? 0 : getPublishTime().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        return result;
    }


}
