package com.example.demo.bean;

import java.util.Date;

/**
 * @Author:Goffy
 */
public class Park {
    /**
     * 距离 非数据库字段
     */
    private Double distance;

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.code
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.name
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.linkman
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.tel
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.email
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.address
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.latitude
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.longitude
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.price
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.picture
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.total
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.empty
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer empty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.company_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.closing_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String closingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.opening_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String openingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.is_free
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer isFree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.park_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer parkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.charging_rules_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer chargingRulesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.secret_key
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String secretKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.interface_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer interfaceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.emptybase
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer emptybase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.parking_type_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer parkingTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.features
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String features;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.plate_number
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String plateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.num
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.charge_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Byte chargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.location_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.rel_park_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer relParkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.flag
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.create_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.update_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.operator_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.is_deferred
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    private Integer isDeferred;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.id
     *
     * @return the value of parking_park.id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.id
     *
     * @param id the value for parking_park.id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.code
     *
     * @return the value of parking_park.code
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.code
     *
     * @param code the value for parking_park.code
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.name
     *
     * @return the value of parking_park.name
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.name
     *
     * @param name the value for parking_park.name
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.type
     *
     * @return the value of parking_park.type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.type
     *
     * @param type the value for parking_park.type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.linkman
     *
     * @return the value of parking_park.linkman
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.linkman
     *
     * @param linkman the value for parking_park.linkman
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.tel
     *
     * @return the value of parking_park.tel
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.tel
     *
     * @param tel the value for parking_park.tel
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.email
     *
     * @return the value of parking_park.email
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.email
     *
     * @param email the value for parking_park.email
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.address
     *
     * @return the value of parking_park.address
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.address
     *
     * @param address the value for parking_park.address
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.latitude
     *
     * @return the value of parking_park.latitude
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.latitude
     *
     * @param latitude the value for parking_park.latitude
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.longitude
     *
     * @return the value of parking_park.longitude
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.longitude
     *
     * @param longitude the value for parking_park.longitude
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.price
     *
     * @return the value of parking_park.price
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.price
     *
     * @param price the value for parking_park.price
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.picture
     *
     * @return the value of parking_park.picture
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.picture
     *
     * @param picture the value for parking_park.picture
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.total
     *
     * @return the value of parking_park.total
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.total
     *
     * @param total the value for parking_park.total
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.empty
     *
     * @return the value of parking_park.empty
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getEmpty() {
        return empty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.empty
     *
     * @param empty the value for parking_park.empty
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setEmpty(Integer empty) {
        this.empty = empty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.company_id
     *
     * @return the value of parking_park.company_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.company_id
     *
     * @param companyId the value for parking_park.company_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.closing_time
     *
     * @return the value of parking_park.closing_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getClosingTime() {
        return closingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.closing_time
     *
     * @param closingTime the value for parking_park.closing_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setClosingTime(String closingTime) {
        this.closingTime = closingTime == null ? null : closingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.opening_time
     *
     * @return the value of parking_park.opening_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getOpeningTime() {
        return openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.opening_time
     *
     * @param openingTime the value for parking_park.opening_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setOpeningTime(String openingTime) {
        this.openingTime = openingTime == null ? null : openingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.is_free
     *
     * @return the value of parking_park.is_free
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.is_free
     *
     * @param isFree the value for parking_park.is_free
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setIsFree(Integer isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.park_type
     *
     * @return the value of parking_park.park_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getParkType() {
        return parkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.park_type
     *
     * @param parkType the value for parking_park.park_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setParkType(Integer parkType) {
        this.parkType = parkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.charging_rules_id
     *
     * @return the value of parking_park.charging_rules_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getChargingRulesId() {
        return chargingRulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.charging_rules_id
     *
     * @param chargingRulesId the value for parking_park.charging_rules_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setChargingRulesId(Integer chargingRulesId) {
        this.chargingRulesId = chargingRulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.secret_key
     *
     * @return the value of parking_park.secret_key
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.secret_key
     *
     * @param secretKey the value for parking_park.secret_key
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey == null ? null : secretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.interface_type
     *
     * @return the value of parking_park.interface_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.interface_type
     *
     * @param interfaceType the value for parking_park.interface_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setInterfaceType(Integer interfaceType) {
        this.interfaceType = interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.emptybase
     *
     * @return the value of parking_park.emptybase
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getEmptybase() {
        return emptybase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.emptybase
     *
     * @param emptybase the value for parking_park.emptybase
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setEmptybase(Integer emptybase) {
        this.emptybase = emptybase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.parking_type_id
     *
     * @return the value of parking_park.parking_type_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getParkingTypeId() {
        return parkingTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.parking_type_id
     *
     * @param parkingTypeId the value for parking_park.parking_type_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setParkingTypeId(Integer parkingTypeId) {
        this.parkingTypeId = parkingTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.features
     *
     * @return the value of parking_park.features
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getFeatures() {
        return features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.features
     *
     * @param features the value for parking_park.features
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setFeatures(String features) {
        this.features = features == null ? null : features.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.plate_number
     *
     * @return the value of parking_park.plate_number
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.plate_number
     *
     * @param plateNumber the value for parking_park.plate_number
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.num
     *
     * @return the value of parking_park.num
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.num
     *
     * @param num the value for parking_park.num
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.charge_type
     *
     * @return the value of parking_park.charge_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Byte getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.charge_type
     *
     * @param chargeType the value for parking_park.charge_type
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setChargeType(Byte chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.location_id
     *
     * @return the value of parking_park.location_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.location_id
     *
     * @param locationId the value for parking_park.location_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.rel_park_id
     *
     * @return the value of parking_park.rel_park_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getRelParkId() {
        return relParkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.rel_park_id
     *
     * @param relParkId the value for parking_park.rel_park_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setRelParkId(Integer relParkId) {
        this.relParkId = relParkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.flag
     *
     * @return the value of parking_park.flag
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.flag
     *
     * @param flag the value for parking_park.flag
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.create_time
     *
     * @return the value of parking_park.create_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.create_time
     *
     * @param createTime the value for parking_park.create_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.update_time
     *
     * @return the value of parking_park.update_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.update_time
     *
     * @param updateTime the value for parking_park.update_time
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.operator_id
     *
     * @return the value of parking_park.operator_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.operator_id
     *
     * @param operatorId the value for parking_park.operator_id
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.is_deferred
     *
     * @return the value of parking_park.is_deferred
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public Integer getIsDeferred() {
        return isDeferred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.is_deferred
     *
     * @param isDeferred the value for parking_park.is_deferred
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    public void setIsDeferred(Integer isDeferred) {
        this.isDeferred = isDeferred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_park
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Park other = (Park) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
                && (this.getLinkman() == null ? other.getLinkman() == null : this.getLinkman().equals(other.getLinkman()))
                && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
                && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
                && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
                && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
                && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
                && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
                && (this.getPicture() == null ? other.getPicture() == null : this.getPicture().equals(other.getPicture()))
                && (this.getTotal() == null ? other.getTotal() == null : this.getTotal().equals(other.getTotal()))
                && (this.getEmpty() == null ? other.getEmpty() == null : this.getEmpty().equals(other.getEmpty()))
                && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
                && (this.getClosingTime() == null ? other.getClosingTime() == null : this.getClosingTime().equals(other.getClosingTime()))
                && (this.getOpeningTime() == null ? other.getOpeningTime() == null : this.getOpeningTime().equals(other.getOpeningTime()))
                && (this.getIsFree() == null ? other.getIsFree() == null : this.getIsFree().equals(other.getIsFree()))
                && (this.getParkType() == null ? other.getParkType() == null : this.getParkType().equals(other.getParkType()))
                && (this.getChargingRulesId() == null ? other.getChargingRulesId() == null : this.getChargingRulesId().equals(other.getChargingRulesId()))
                && (this.getSecretKey() == null ? other.getSecretKey() == null : this.getSecretKey().equals(other.getSecretKey()))
                && (this.getInterfaceType() == null ? other.getInterfaceType() == null : this.getInterfaceType().equals(other.getInterfaceType()))
                && (this.getEmptybase() == null ? other.getEmptybase() == null : this.getEmptybase().equals(other.getEmptybase()))
                && (this.getParkingTypeId() == null ? other.getParkingTypeId() == null : this.getParkingTypeId().equals(other.getParkingTypeId()))
                && (this.getFeatures() == null ? other.getFeatures() == null : this.getFeatures().equals(other.getFeatures()))
                && (this.getPlateNumber() == null ? other.getPlateNumber() == null : this.getPlateNumber().equals(other.getPlateNumber()))
                && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
                && (this.getChargeType() == null ? other.getChargeType() == null : this.getChargeType().equals(other.getChargeType()))
                && (this.getLocationId() == null ? other.getLocationId() == null : this.getLocationId().equals(other.getLocationId()))
                && (this.getRelParkId() == null ? other.getRelParkId() == null : this.getRelParkId().equals(other.getRelParkId()))
                && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
                && (this.getIsDeferred() == null ? other.getIsDeferred() == null : this.getIsDeferred().equals(other.getIsDeferred()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_park
     *
     * @mbg.generated Tue Jan 15 14:38:17 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getLinkman() == null) ? 0 : getLinkman().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
        result = prime * result + ((getTotal() == null) ? 0 : getTotal().hashCode());
        result = prime * result + ((getEmpty() == null) ? 0 : getEmpty().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getClosingTime() == null) ? 0 : getClosingTime().hashCode());
        result = prime * result + ((getOpeningTime() == null) ? 0 : getOpeningTime().hashCode());
        result = prime * result + ((getIsFree() == null) ? 0 : getIsFree().hashCode());
        result = prime * result + ((getParkType() == null) ? 0 : getParkType().hashCode());
        result = prime * result + ((getChargingRulesId() == null) ? 0 : getChargingRulesId().hashCode());
        result = prime * result + ((getSecretKey() == null) ? 0 : getSecretKey().hashCode());
        result = prime * result + ((getInterfaceType() == null) ? 0 : getInterfaceType().hashCode());
        result = prime * result + ((getEmptybase() == null) ? 0 : getEmptybase().hashCode());
        result = prime * result + ((getParkingTypeId() == null) ? 0 : getParkingTypeId().hashCode());
        result = prime * result + ((getFeatures() == null) ? 0 : getFeatures().hashCode());
        result = prime * result + ((getPlateNumber() == null) ? 0 : getPlateNumber().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getChargeType() == null) ? 0 : getChargeType().hashCode());
        result = prime * result + ((getLocationId() == null) ? 0 : getLocationId().hashCode());
        result = prime * result + ((getRelParkId() == null) ? 0 : getRelParkId().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getIsDeferred() == null) ? 0 : getIsDeferred().hashCode());
        return result;
    }

}
